name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install package
        run: |
          npm install
          npm run dist
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
          fqdn: u.ehhh.eu.org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
